# R package installation script after update

install.packages('pak')
pak::pkg_install(c(	# Essentials
					'tidyverse',
					'knitr',
					'rmarkdown',
					'shiny',
					'here',
					'glue',
					'reshape2',
					'remotes',
					# Plotting
					'ggforce',
					'ggthemes',
					'ggsignif',
					'ggpubr',
					'ggbeeswarm',
					'viridis',
					'BlandAltmanLeh',
					'png',
					'grid',
					'plotly',
					'yarrr',
					'extrafont',
					# Other presentation tools (tables etc.)
					'gt',
					'gtsummary',
					'qwraps2',
					'sjPlot',
					'DiagrammeR',
					# Various analysis tools
					'arsenal',
					'caret',
					'DescTools',
					'digest',
					'DT',
					'glmnet',
					'irr',
					'jsonlite',
					'lme4',
					'mada',
					'meta',
					'oro.dicom',
					'oro.nifti',
					'pROC',
					'psych',
					'pvrank',
					'quantreg',
					'rsample',
					'RISmed',
					'survival',
					'tidytext',
					'zoo'))
